### ISSUE TITLE
move temperature credentials to another file

### ISSUE THREAD

**Issue by petr-tik** [terryspitz/ipython_notebooks#1]
as per email. Currently, credentials are in plaintext in the temperature notebook. 

It might be safer to keep the URL and auth details in a config.json file, add that to gitignore, and upload temperature.py and config.json to the same VM. In the temperature file you can add something like:

```
import json

creds = json.load("config.json")
url, auth_email, auth_pass = creds["url"], creds["auth_email"], creds["auth_pass"]
r = requests.get(url, auth=(auth_email, auth_pass))
```

**Comment by terryspitz** [comment]
Done in https://github.com/terryspitz/temperature, thanks Petr!
